### ISSUE TITLE
⚙️ Airbnb 스타일로 eslint, prettier 설정하기

### ISSUE THREAD

**Issue by cho-hyeonjin** [f-lab-edu/toss-blog-clone#1]
## Tasks
- [ ] Airbnb 스타일로 eslint 설정하기
- [ ] Airbnb 스타일로 prettier 설정하기
- [ ] PR, Commit Form 만들기

## Explain

**Comment by cho-hyeonjin** [comment]
Related Issue #2 feat: Airbnb 방식에 따른 코드 컨벤션 설정

해당 PR에 사용한 ESLint, Prettier 옵션에 대해 comment로 정리해 두었습니다. :)
